apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: achedehd/ubuntu_con_apache
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
  namespace: default
spec:
  selector:
    app: mi-aplicacion
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 80
