name: Docker Image CI

# Trigger / Sensor / Gatillo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Acción
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd App/Pablo  && docker build . --file Dockerfile --tag pabloapp:$(date +%s)
