name: terraform plan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


     - name: Run Terraform Apply
        if: github.event.review.state == 'approved'
        run: |
          for env in dev QA staging prod
          do
            terraform workflow list
            terraform workflow select $env
            terraform init 
            terraform apply -target="module.dashboards" \
              -target="module.alert-rules" \
              -var="TF_VAR_environment=$env" \
              --auto-approve
          done
  
